version: '3.1'
services:
  livedeck-server:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile
    restart: always
    ports:
      - "4000:4000"
      - "5000:5000"
    container_name: livedeck_server
    command: "node /app/src/index"
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
    links:
      - livedeck-server-db
    environment:
      - APP_JWT_SIGN_KEY=rUOIUnNOQlUwUhhN8Zk6
      - APP_WEBSOCKET_PORT=5000

  livedeck-server-db:
    image: mysql
    restart: always
    ports:
      - "4001:3306"
    container_name: livedeck_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: livedeck_database
    volumes:
      - dbvolume:/var/lib/mysql
volumes:
  dbvolume:
networks:
  default:
    external:
      name: livedeck
